name: 哈喽

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0,12 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        HLDSP_HD: ${{ secrets.HLDSP_HD }}
        HLDSP_URL: ${{ secrets.HLDSP_URL }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.HLDSP_HD
        run: |
          npm install
      - name: '运行 【哈喽短视频】'
        if: env.HLDSP_HD
        run: |
          node Task/hldsp.js
