
name: 聚看点极速版

on:
  workflow_dispatch:
  schedule:
     - cron: '*/28 */4 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JUKAN_COOKIE: ${{ secrets.JUKAN_COOKIE }}
        JUKAN_BODY: ${{ secrets.JUKAN_BODY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ickel00/Yth2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
      - name: '运行 【聚看点极速版】'
        if: env.JUKAN_COOKIE
        run: |
          node Task/jukanspeed.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
